version: "3.3"

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

services:

### Zabbix Web #############################################

  zabbix-web:
    build:
      context: ./zabbix-web
      args:
        - ZABBIX_WEB_VERSION=${ZABBIX_WEB_VERSION}
    container_name: ${ZABBIX_WEB_CONTAINER_NAME}-${ZABBIX_WEB_VERSION}
    restart: on-failure
    ports: 
      - ${ZABBIX_WEB_PORT}:80
    networks:
      - backend
      - frontend
    environment: 
      - DB_SERVER_HOST=${ZABBIX_WEB_DB_SERVER_HOST}
      - MYSQL_DATABASE=${ZABBIX_WEB_MYSQL_DATABASE}
      - MYSQL_USER=${ZABBIX_WEB_MYSQL_USER}
      - MYSQL_PASSWORD=${ZABBIX_WEB_MYSQL_PASSWORD}
      - ZBX_SERVER_HOST=${ZABBIX_WEB_ZBX_SERVER_HOST}
      - PHP_TZ=${ZABBIX_WEB_PHP_TZ}

### Grafana ################################################
  
  grafana:
    build:
      context: ./grafana
      args:
        - GRAFANA_VERSION=${GRAFANA_VERSION}
    container_name: ${GRAFANA_CONTAINER_NAME}-${GRAFANA_VERSION}
    restart: on-failure
    volumes: 
      - ${GF_PATHS_DATA}:/var/lib/grafana
      - ${GF_PATHS_LOGS}:/var/log/grafana
    ports:
      - ${GRAFANA_PORT}:3000
    networks:
      - backend
      - frontend
    environment:
      - GF_INSTALL_PLUGINS=${GF_INSTALL_PLUGINS}
      - GF_LOG_MODE=${GF_LOG_MODE}